const { ROUTER_PARAMS } = require('../../config/router')

const CATEGORY = '/category'
const CATEGORY_CREATE = `${CATEGORY}/create/:${ROUTER_PARAMS.USER_ID}`
const CATEGORY_DETAILS = `${CATEGORY}/:${ROUTER_PARAMS.CATEGORY_ID}`
const CATEGORY_UPDATE = `${CATEGORY}/:${ROUTER_PARAMS.CATEGORY_ID}/:${ROUTER_PARAMS.USER_ID}`
const CATEGORY_DELETE = `${CATEGORY}/:${ROUTER_PARAMS.CATEGORY_ID}/:${ROUTER_PARAMS.USER_ID}`

const CATEGORIES = '/categories'

module.exports = {
  CATEGORY,
  CATEGORY_CREATE,
  CATEGORIES,
  CATEGORY_DETAILS,
  CATEGORY_UPDATE,
  CATEGORY_DELETE
}
