const { ROUTER_PARAMS } = require('../../config/router')
const { CATEGORIES } = require('../category/requestPaths')

const PRODUCT = '/product'
const PRODUCT_CREATE = `${PRODUCT}/create/:${ROUTER_PARAMS.USER_ID}`
const PRODUCT_DETAILS = `${PRODUCT}/:${ROUTER_PARAMS.PRODUCT_ID}`
const PRODUCT_UPDATE = `${PRODUCT}/:${ROUTER_PARAMS.PRODUCT_ID}/:${ROUTER_PARAMS.USER_ID}`
const PRODUCT_DELETE = `${PRODUCT}/:${ROUTER_PARAMS.PRODUCT_ID}/:${ROUTER_PARAMS.USER_ID}`

const PRODUCTS = '/products'
const PRODUCTS_RELATED = `${PRODUCTS}/related/:${ROUTER_PARAMS.PRODUCT_ID}`
const PRODUCTS_CATEGORIES = `${PRODUCTS}${CATEGORIES}`

const PRODUCTS_BY_SEARCH = `${PRODUCTS}/by/search`
const PRODUCT_PHOTO = `${PRODUCT}/photo/:${ROUTER_PARAMS.PRODUCT_ID}`

module.exports = {
  PRODUCT,
  PRODUCT_CREATE,
  PRODUCT_DETAILS,
  PRODUCT_UPDATE,
  PRODUCT_DELETE,
  PRODUCTS,
  PRODUCTS_RELATED,
  PRODUCTS_CATEGORIES,
  PRODUCTS_BY_SEARCH,
  PRODUCT_PHOTO
}
